name: CDF

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 5

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: yarn

      - name: Spider
        run: npm run serve
        env:
          DB_URI: ${{ secrets.DB_URI }}
          TARGET_URL: ${{ secrets.TARGET_URL }}
          WEBHOOK: ${{ secrets.WEBHOOK }}
          SECRET: ${{ secrets.SECRET }}
