name: schedule

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: yarn

      - name: Spider
        run: npm run serve
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
          SECRET: ${{ secrets.SECRET }}

      - name: Push commit
        run: chmod +x ./git-status.sh && ./git-status.sh
